#! /bin/sh
set -e
opt=
while :; do
	case $1 in
	-*)	opt=$opt${1#-};;
	*)	break;;
	esac
	shift
done
os=${1:-$(uname)}-$(uname -m)
case $0 in
/*)	srcdir=${0%/*}/..;;
*)	srcdir=$(pwd)
esac
outdir=$srcdir/OUT
pname=dropbearx-$os
bdir=$outdir/build-$os
pdir=$outdir/$pname
case $opt in *n*);;*)	rm -fr "$bdir" "$pdir"; esac
mkdir -p "$bdir" "$pdir"
onexit(){ if [ "$?" != 0 ]; then echo FAILED; fi; }
trap onexit EXIT
case $opt in *r*);;*)
	autoreconf -i "$srcdir"
	# wtf
	if [ ! -f "$srcdir/config.sub" ]; then
		cp /usr/share/automake*/config.* /usr/share/automake*/install*sh "$srcdir"
	fi
esac
cd "$bdir"
case $opt in *c*);;*)	"$srcdir/configure" --prefix="$pdir"; esac
make=${make:-make}
$make -j32
$make strip
$make install
tar -C "$outdir" -zcf "$outdir/$pname.tgz" "$pname"
$srcdir/util/simple-test
echo "OK, output in $outdir/$pname.tgz"
