#! /bin/sh
set -e
opt=
while :; do
	case $1 in
	-*)	opt=$opt${1#-};;
	*)	break;;
	esac
	shift
done
os=${1:-$(uname)}-$(uname -m)
case $0 in
/*)	srcdir=${0%/*}/..;;
*)	srcdir=$(pwd)
esac
outdir=$srcdir/OUT
bdir=$outdir/build-$os
pdir=$outdir/inst-$os
case $opt in *n*);;*)	rm -fr "$bdir" "$pdir"; esac
mkdir -p "$bdir" "$pdir"
onexit(){
	err=$?
	if [ "$err" = 0 ]; then
		echo "OK, $bdir done"
	else
		echo FAILED
	fi
}
trap onexit EXIT
set -x
case $opt in *n*);;*)
	autoreconf -i "$srcdir"
	# wtf
	if [ ! -f "$srcdir/config.sub" ]; then
		cp /usr/share/automake*/config.* /usr/share/automake*/install*sh "$srcdir"
	fi
esac
cd "$bdir"
case $opt in *n*);;*)	"$srcdir/configure" --prefix="$pdir"; esac
make -j32
# make check
make strip
make install
tar -C "$pdir" -zcf "$outdir/dropbearx-$os.tgz" .
$srcdir/util/simple-test
