name: Build with the NDK
on:
  push:
    branches:
      - fixes
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:
jobs:
  test:
    uses: turistu/odds-n-ends/.github/workflows/build-with-ndk.yml@main
    with:
      reconf: autoreconf -i
      build: .github/build-with-ndk
