name: Build with Android's NDK
on:
  push:
    branches:
      - fixes
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, x86_64, armv7a, i686]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache the downloaded NDK
        id: cache-ndk
        uses: actions/cache@v3
        with:
          key: ${{runner.os}}-android-ndk
          path: tools
      - name: Download the NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          wget -nv https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -d tools android-ndk-*-linux.zip

      - name: Build with the NDK
        id: build
        run: scripts/build-with-ndk dropbearx-android-${{matrix.arch}} ${{matrix.arch}}

      - name: Save output
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: dropbearx-android-${{matrix.arch}}${{steps.build.conclusion == 'failure' && '-FAILED' || ''}}
          path: dropbearx-android-${{matrix.arch}}
